CREATE TABLE IF NOT EXISTS sg_order_import_batch (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    original_file_name VARCHAR(255) NOT NULL COMMENT '原始文件名',
    file_size BIGINT NOT NULL DEFAULT 0 COMMENT '文件大小',
    parse_status VARCHAR(32) NOT NULL COMMENT '解析状态：SUCCESS/FAILED',
    parsed_order_count INT NOT NULL DEFAULT 0 COMMENT '解析出的有效订单数量',
    parse_error_json JSON NOT NULL COMMENT '解析错误或提示',
    parsed_payload_json JSON NOT NULL COMMENT '解析出的订单卡片数据',
    uploader_id BIGINT NOT NULL COMMENT '上传管理员 ID',
    uploader_name VARCHAR(64) NOT NULL COMMENT '上传管理员名称',
    uploaded_at DATETIME NOT NULL COMMENT '上传时间',
    creator VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    KEY idx_order_import_uploaded_at (uploaded_at),
    KEY idx_order_import_status (parse_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='订单 Excel 导入批次表';

CREATE TABLE IF NOT EXISTS sg_order_generation_config (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    year_no INT NOT NULL COMMENT '年份',
    market_code VARCHAR(32) NOT NULL COMMENT '市场：LOCAL/REGIONAL/NATIONAL/GLOBAL',
    order_type VARCHAR(32) NOT NULL COMMENT '订单类型',
    order_count INT NOT NULL DEFAULT 0 COMMENT '该标段生成订单数量',
    release_sequence_no INT NOT NULL COMMENT '全年标段释放顺序',
    source_batch_id BIGINT NULL COMMENT '来源 Excel 解析批次',
    config_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '配置状态：DRAFT/LOCKED',
    creator VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_generation_config (year_no, market_code, order_type),
    UNIQUE KEY uk_order_release_sequence (year_no, release_sequence_no),
    KEY idx_year_market (year_no, market_code),
    KEY idx_source_batch (source_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='订单生成数量与释放顺序配置表';

CREATE TABLE IF NOT EXISTS sg_order_pool (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    year_no INT NOT NULL COMMENT '年份',
    market_code VARCHAR(32) NOT NULL COMMENT '市场',
    order_type VARCHAR(32) NOT NULL COMMENT '订单类型',
    order_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '订单金额',
    order_quantity DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '数量',
    unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '单价',
    account_term INT NOT NULL DEFAULT 0 COMMENT '账期，单位季度',
    pool_status VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE' COMMENT '订单池状态：AVAILABLE/SELECTED/VOID',
    selected_group_id BIGINT NULL COMMENT '选中小组 ID',
    source_batch_id BIGINT NULL COMMENT '来源 Excel 批次',
    source_sheet_name VARCHAR(64) NULL COMMENT '来源 sheet',
    source_cell VARCHAR(16) NULL COMMENT '来源订单卡片起始单元格',
    source_row_index INT NULL COMMENT '来源解析序号',
    creator VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    KEY idx_order_pool_year_market (year_no, market_code, order_type),
    KEY idx_order_pool_status (pool_status),
    KEY idx_order_pool_selected_group (selected_group_id),
    KEY idx_order_pool_source_batch (source_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='固定订单池表';

CREATE TABLE IF NOT EXISTS sg_market_bidding_state (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    year_no INT NOT NULL COMMENT '年份',
    market_code VARCHAR(32) NOT NULL COMMENT '市场',
    order_type VARCHAR(32) NOT NULL COMMENT '订单类型',
    segment_code VARCHAR(64) NOT NULL COMMENT '标段编码',
    release_sequence_no INT NOT NULL COMMENT '标段释放顺序',
    segment_status VARCHAR(32) NOT NULL COMMENT '标段状态',
    leader_group_id BIGINT NULL COMMENT '市场龙头小组 ID',
    leader_rule_json JSON NULL COMMENT '市场龙头计算依据',
    random_seed VARCHAR(64) NULL COMMENT '随机排序种子或结果摘要',
    current_group_id BIGINT NULL COMMENT '当前轮到的小组',
    opened_at DATETIME NULL COMMENT '开放投入时间',
    closed_at DATETIME NULL COMMENT '关闭投入时间',
    released_at DATETIME NULL COMMENT '标段释放时间',
    completed_at DATETIME NULL COMMENT '标段完成时间',
    creator VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_market_bidding_state (year_no, market_code, order_type),
    UNIQUE KEY uk_segment_release_sequence (year_no, release_sequence_no),
    KEY idx_segment_status (segment_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='订单标段竞标状态表';

CREATE TABLE IF NOT EXISTS sg_group_market_bid (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    group_id BIGINT NOT NULL COMMENT '小组 ID',
    year_no INT NOT NULL COMMENT '年份',
    market_code VARCHAR(32) NOT NULL COMMENT '市场',
    market_investment DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '市场投入',
    submitted_at DATETIME NOT NULL COMMENT '提交时间',
    creator VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_group_year_market_bid (group_id, year_no, market_code),
    KEY idx_year_market_bid (year_no, market_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='小组年度市场投入表';

CREATE TABLE IF NOT EXISTS sg_market_selection_order (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    year_no INT NOT NULL COMMENT '年份',
    market_code VARCHAR(32) NOT NULL COMMENT '市场',
    order_type VARCHAR(32) NOT NULL COMMENT '订单类型',
    sequence_no INT NOT NULL COMMENT '选单顺序',
    group_id BIGINT NOT NULL COMMENT '小组 ID',
    market_investment DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '排序时市场投入',
    previous_market_order_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '上一年度该市场订单总额',
    is_market_leader TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否市场龙头',
    rank_basis_json JSON NOT NULL COMMENT '排序依据与随机结果',
    selection_status VARCHAR(32) NOT NULL DEFAULT 'WAITING' COMMENT '选单状态',
    selected_order_id BIGINT NULL COMMENT '已选订单 ID',
    selected_at DATETIME NULL COMMENT '选择时间',
    skipped_by_admin_id BIGINT NULL COMMENT '管理员代跳过操作人',
    skipped_reason VARCHAR(255) NULL COMMENT '管理员代跳过原因',
    skipped_at DATETIME NULL COMMENT '管理员代跳过时间',
    creator VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_market_sequence (year_no, market_code, order_type, sequence_no),
    UNIQUE KEY uk_group_market_sequence (year_no, market_code, order_type, group_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='订单标段选单顺序表';

CREATE TABLE IF NOT EXISTS sg_group_order_selection (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    group_id BIGINT NOT NULL COMMENT '小组 ID',
    year_no INT NOT NULL COMMENT '年份',
    market_code VARCHAR(32) NOT NULL COMMENT '市场',
    order_type VARCHAR(32) NOT NULL COMMENT '订单类型',
    order_id BIGINT NOT NULL COMMENT '订单 ID',
    selection_status VARCHAR(32) NOT NULL DEFAULT 'SELECTED' COMMENT '选择状态',
    delivery_status VARCHAR(32) NOT NULL DEFAULT 'SELECTED' COMMENT '交付状态',
    delivered_stage_code VARCHAR(16) NULL COMMENT '交付季度',
    delivered_at DATETIME NULL COMMENT '交付时间',
    selected_at DATETIME NOT NULL COMMENT '选择时间',
    creator VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_group_year_segment_selection (group_id, year_no, market_code, order_type),
    UNIQUE KEY uk_order_selected (order_id),
    KEY idx_group_year_order_selection (group_id, year_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='小组订单选择与交付状态表';
