CREATE TABLE IF NOT EXISTS sg_group_order_delivery_revision (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    selection_id BIGINT NOT NULL COMMENT '小组订单选择记录 ID',
    group_id BIGINT NOT NULL COMMENT '小组 ID',
    year_no INT NOT NULL COMMENT '年份',
    order_id BIGINT NOT NULL COMMENT '订单 ID',
    revision_type VARCHAR(32) NOT NULL COMMENT '修订类型：DELIVERED / INVALIDATED',
    stage_code VARCHAR(16) NULL COMMENT '交付或失效关联阶段',
    order_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '订单金额快照',
    effective_before TINYINT(1) NOT NULL DEFAULT 0 COMMENT '修订前是否有效',
    effective_after TINYINT(1) NOT NULL DEFAULT 0 COMMENT '修订后是否有效',
    rollback_log_id BIGINT NULL COMMENT '由退回重提或恢复快照导致失效时对应回退日志',
    operated_by_id BIGINT NULL COMMENT '操作人 ID',
    operated_by_name VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '操作人名称',
    operated_at DATETIME NOT NULL COMMENT '操作时间',
    remark VARCHAR(255) NULL COMMENT '备注',
    creator VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    KEY idx_order_delivery_revision_selection (selection_id, operated_at),
    KEY idx_order_delivery_revision_group_year (group_id, year_no, stage_code),
    KEY idx_order_delivery_revision_rollback (rollback_log_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='小组订单交付修订历史表';
